# Bind this Kubernetes service account to its Google service account using GKE Workload Identity.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kionga-secret-reader
  namespace: kionga-system
  annotations:
    iam.gke.io/gcp-service-account: kionga-secret-reader@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: kionga-store
  namespace: kionga-system
spec:
  provider:
    gcpsm:
      projectID: PROJECT_ID
      auth:
        workloadIdentity:
          clusterLocation: CLUSTER_LOCATION
          clusterName: CLUSTER_NAME
          clusterProjectID: PROJECT_ID
          serviceAccountRef: {name: kionga-secret-reader}
